services:
  clickhouse:
    image: clickhouse/clickhouse-server:22.12
    ports:
      - 8123:8123
      - 9000:9000

  vertica:
    image: jbfavre/vertica:9.x
    ports:
      - 5433:5433

  jupyter:
    image: jupyter/minimal-notebook:python-3.10
    ports:
      - 8888:8888
    volumes:
      - ./research.ipynb:/home/jovyan/work/research.ipynb
    entrypoint: >
      sh -c "pip install -r requirements.txt --no-cache-dir &&
             jupyter notebook --port=8888 --no-browser --ip=0.0.0.0 --allow-root"