services:
  fastapi:
    image: temirovazat/event_sourcing:1.0.0
    env_file:
      - ./.env
    environment:
      FASTAPI_DEBUG: True

  pyspark:
    image: temirovazat/kafka_to_clickhouse:1.0.0
    restart: always
    environment:
      CLICKHOUSE_HTTP_PORT: 8123
    env_file:
      - ./.env

  kafka:
    image: confluentinc/cp-kafka:7.3.1
    expose:
      - 29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true

  clickhouse-node1:
    image: clickhouse/clickhouse-server:22.12
    expose:
      - 8123
      - 9000
    volumes:
      - ./data/node1:/etc/clickhouse-server
      - ./data/shard1.sql:/docker-entrypoint-initdb.d/init.sql
    depends_on:
      - zookeeper
  clickhouse-node2:
    image: clickhouse/clickhouse-server:22.12
    volumes:
      - ./data/node2:/etc/clickhouse-server
    depends_on:
      - zookeeper
  clickhouse-node3:
    image: clickhouse/clickhouse-server:22.12
    volumes:
      - ./data/node3:/etc/clickhouse-server
      - ./data/shard2.sql:/docker-entrypoint-initdb.d/init.sql
    depends_on:
      - zookeeper
  clickhouse-node4:
    image: clickhouse/clickhouse-server:22.12
    volumes:
      - ./data/node4:/etc/clickhouse-server
    depends_on:
      - zookeeper

  zookeeper:
    image: zookeeper:3.8

  nginx:
    image: nginx:1.23.2
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - fastapi
